var allResult = {
  mode: "all",
  tests: [
    // Problem 1 written
    {
      number: "1a",
      name: "Choose Your AI Product",
      description: "Choose Your AI Product",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },

    // Problem 2 written
    {
      number: "2a",
      name: "Product Purpose and Usage",
      description: "Product Purpose and Usage",
      max_seconds: null,
      max_points: 5,
      extra_credit: false,
      basic: false,
    },
    {
      number: "2b",
      name: "Recent News and Developments",
      description: "Recent News and Developments",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "2c",
      name: "Company & Product Mission Alignment",
      description: "Company & Product Mission Alignment",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    {
      number: "2d",
      name: "Product Pricing and Access",
      description: "Product Pricing and Access",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    {
      number: "3a",
      name: "Product User Base and Demographics",
      description: "Product User Base and Demographics",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "3b",
      name: "Intended Use Cases and Audience",
      description: "Intended Use Cases and Audience",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "3c",
      name: "Market Share and Competitors",
      description: "Market Share and Competitors",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "3d",
      name: "Misuse Risks and Company Safeguards",
      description: "Misuse Risks and Company Safeguards",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "3e",
      name: "Gaps and Unintended Use Cases",
      description: "Gaps and Unintended Use Cases",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    {
      number: "4a",
      name: "Marketing Channels and Discovery",
      description: "Marketing Channels and Discovery",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "4b",
      name: "Marketing Strategy and Mission Alignment",
      description: "Marketing Strategy and Mission Alignment",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "4c",
      name: "Feedback, Help, and Customer Support",
      description: "Feedback, Help, and Customer Support",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "4d",
      name: "Submitting Customer Support Queries",
      description: "Submitting Customer Support Queries",
      max_seconds: null,
      max_points: 5,
      extra_credit: false,
      basic: false,
    },
    // Problem 5 written
    {
      number: "5a",
      name: "Benchmarking Disparities and Biases",
      description: "Benchmarking Disparities and Biases",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "5b",
      name: "Running and Documenting Results",
      description: "Running and Documenting Results",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    {
      number: "5c",
      name: "Analyzing Disparities and Practical Impacts",
      description: "Analyzing Disparities and Practical Impacts",
      max_seconds: null,
      max_points: 5,
      extra_credit: false,
      basic: false,
    },
    {
      number: "5d",
      name: "User Rights and Platform Responsibilities",
      description: "User Rights and Platform Responsibilities",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    {
      number: "5e",
      name: "Proposing Follow-Up Tests or Analyses",
      description: "Proposing Follow-Up Tests or Analyses",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    // Problem 6 written
    {
      number: "6a",
      name: "Data Collection and Use Policies",
      description: "Data Collection and Use Policies",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    {
      number: "6b",
      name: "Transparency and Trust Analysis",
      description: "Transparency and Trust Analysis",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    {
      number: "6c",
      name: "Fairness, Transparency, and Accountability in Practice",
      description: "Fairness, Transparency, and Accountability in Practice",
      max_seconds: null,
      max_points: 5,
      extra_credit: false,
      basic: false,
    },
    {
      number: "6d",
      name: "User Empowerment and Accountability Tools",
      description: "User Empowerment and Accountability Tools",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "6e",
      name: "Copyright and Fair Use",
      description: "Copyright and Fair Use",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    // Problem 7 written
    {
      number: "7a",
      name: "Job Tasks and Potential for Displacement",
      description: "Job Tasks and Potential for Displacement",
      max_seconds: null,
      max_points: 2,
      extra_credit: false,
      basic: false,
    },
    {
      number: "7b",
      name: "Job Displacement vs. Augmentation",
      description: "Job Displacement vs. Augmentation",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "7c",
      name: "Societal Inequalities",
      description: "Societal Inequalities",
      max_seconds: null,
      max_points: 3,
      extra_credit: false,
      basic: false,
    },
    {
      number: "7d",
      name: "Strategies and Mitigation Measures",
      description: "Strategies and Mitigation Measures",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },
    // Problem 8 written
    {
      number: "8a",
      name: "Summarize and Improve Your Product",
      description: "Summarize and Improve Your Product",
      max_seconds: null,
      max_points: 8,
      extra_credit: false,
      basic: false,
    },
    {
      number: "8b",
      name: "Power and Responsibility in Building AI",
      description: "Power and Responsibility in Building AI",
      max_seconds: null,
      max_points: 4,
      extra_credit: false,
      basic: false,
    },

    // // Problem 2 code
    // {
    //   number: "2b-0-basic",
    //   name: "gradient_warmup deterministic",
    //   description: "gradient_warmup deterministic",
    //   max_seconds: 5,
    //   max_points: 1,
    //   extra_credit: false,
    //   basic: true,
    // },
    // {
    //   number: "2b-1-hidden",
    //   name: "gradient_warmup randomized",
    //   description: "gradient_warmup randomized",
    //   max_seconds: 5,
    //   max_points: 2,
    //   extra_credit: false,
    //   basic: false,
    // },
    // {
    //   number: "2d-0-basic",
    //   name: "matrix_grad deterministic",
    //   description: "matrix_grad deterministic",
    //   max_seconds: 5,
    //   max_points: 1,
    //   extra_credit: false,
    //   basic: true,
    // },
    // {
    //   number: "2d-1-hidden",
    //   name: "matrix_grad randomized",
    //   description: "matrix_grad randomized + numeric check",
    //   max_seconds: 5,
    //   max_points: 2,
    //   extra_credit: false,
    //   basic: false,
    // },
    // {
    //   number: "2e-0-basic",
    //   name: "finite differences single case",
    //   description: "finite differences matches analytic gradient (single case)",
    //   max_seconds: 5,
    //   max_points: 1,
    //   extra_credit: false,
    //   basic: true,
    // },
    // {
    //   number: "2e-1-hidden",
    //   name: "finite differences randomized",
    //   description:
    //     "finite differences matches analytic gradient (random cases)",
    //   max_seconds: 5,
    //   max_points: 2,
    //   extra_credit: false,
    //   basic: false,
    // },

    // // Problem 3 written
    // {
    //   number: "3a",
    //   name: "Weighted scalar quadratic minimizer",
    //   description: "Weighted scalar quadratic minimizer",
    //   max_seconds: null,
    //   max_points: 3,
    //   extra_credit: false,
    //   basic: false,
    // },
    // {
    //   number: "3b",
    //   name: "Gradient descent tutor session link",
    //   description: "Gradient descent tutor session link",
    //   max_seconds: null,
    //   max_points: 2,
    //   extra_credit: false,
    //   basic: false,
    // },

    // // Problem 3 code
    // {
    //   number: "3c-0-basic",
    //   name: "GD quadratic deterministic",
    //   description:
    //     "gradient descent converges to weighted average (deterministic)",
    //   max_seconds: 5,
    //   max_points: 1,
    //   extra_credit: false,
    //   basic: true,
    // },
    // {
    //   number: "3c-1-hidden",
    //   name: "GD quadratic randomized",
    //   description: "gradient descent converges on random instances",
    //   max_seconds: 5,
    //   max_points: 2,
    //   extra_credit: false,
    //   basic: false,
    // },

    // // Problem 4 (Ethics in AI) written
    // {
    //   number: "4a",
    //   name: "Ethics in AI part a",
    //   description: "Ethics in AI part a",
    //   max_seconds: null,
    //   max_points: 2,
    //   extra_credit: false,
    //   basic: false,
    // },
    // {
    //   number: "4b",
    //   name: "Ethics in AI part b",
    //   description: "Ethics in AI part b",
    //   max_seconds: null,
    //   max_points: 2,
    //   extra_credit: false,
    //   basic: false,
    // },
    // {
    //   number: "4c",
    //   name: "Ethics in AI part c",
    //   description: "Ethics in AI part c",
    //   max_seconds: null,
    //   max_points: 2,
    //   extra_credit: false,
    //   basic: false,
    // },
    // {
    //   number: "4d",
    //   name: "Ethics in AI part d",
    //   description: "Ethics in AI part d",
    //   max_seconds: null,
    //   max_points: 2,
    //   extra_credit: false,
    //   basic: false,
    // },
  ],
  leaderboard: [],
};
